apiVersion: v1
kind: Service
metadata:
  name: flask-notes-service
  namespace: prod
  labels:
    app: flask-notes
spec:
  type: NodePort
  selector:
    app: flask-notes
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30091
